// scripts/chaos/features/logistics/util/insightReasonCodes.js

export const ReasonCodes = Object.freeze({
  NO_EDGE_GRAPH: "NO_EDGE_GRAPH",
  NO_ADJACENT_INV: "NO_ADJACENT_INV",
  INV_EMPTY: "INV_EMPTY",
  RESOLVE_NONE: "RESOLVE_NONE",
  THROTTLED: "THROTTLED",
  MUTATION_FAIL: "MUTATION_FAIL",
  EXPORT_THROTTLED: "EXPORT_THROTTLED",
  EXPORT_NO_INVENTORIES: "EXPORT_NO_INVENTORIES",
  EXPORT_NO_ITEMS: "EXPORT_NO_ITEMS",

  RESOLVE_NO_ATTUNED: "RESOLVE_NO_ATTUNED",
  RESOLVE_ATTUNED_FULL: "RESOLVE_ATTUNED_FULL",
  RESOLVE_ATTUNED_NO_PATH: "RESOLVE_ATTUNED_NO_PATH",
  RESOLVE_DRIFT_ALL_FILTERED: "RESOLVE_DRIFT_ALL_FILTERED",
  RESOLVE_DRIFT_NO_INVENTORIES: "RESOLVE_DRIFT_NO_INVENTORIES",
  RESOLVE_DRIFT_ALL_FULL: "RESOLVE_DRIFT_ALL_FULL",
  RESOLVE_DRIFT_NO_PATH: "RESOLVE_DRIFT_NO_PATH",
  RESOLVE_CRUCIBLE_NO_PATH: "RESOLVE_CRUCIBLE_NO_PATH",
  RESOLVE_FOUNDRY_NO_PATH: "RESOLVE_FOUNDRY_NO_PATH",
  RESOLVE_SAME_CONTAINER: "RESOLVE_SAME_CONTAINER",
  ILLEGAL_MUTATION_DETECTED: "ILLEGAL_MUTATION_DETECTED",
  ILLEGAL_MUTATION_BLOCKED: "ILLEGAL_MUTATION_BLOCKED",
  TRANSFER_WITHOUT_INFLIGHT: "TRANSFER_WITHOUT_INFLIGHT",
  SPAWN_EXTRACT: "SPAWN_EXTRACT",
  SETTLEMENT_INSERT: "SETTLEMENT_INSERT",
  EXTRACT_WITHOUT_RESOLVE: "EXTRACT_WITHOUT_RESOLVE",
  SPAWN_WITHOUT_PATH: "SPAWN_WITHOUT_PATH",
  SETTLE_WITHOUT_INFLIGHT: "SETTLE_WITHOUT_INFLIGHT",
  SETTLE_SAME_TICK_AS_SPAWN: "SETTLE_SAME_TICK_AS_SPAWN",
  SETTLE_TOO_FAST: "SETTLE_TOO_FAST",

  EDGE_MISSING_PRECHECK: "EDGE_MISSING_PRECHECK",
  EDGE_BROKEN_DROP: "EDGE_BROKEN_DROP",

  WALK_NO_ATTUNED: "WALK_NO_ATTUNED",
  WALK_DRIFT_LOST: "WALK_DRIFT_LOST",
  WALK_DRIFT_ROUTE: "WALK_DRIFT_ROUTE",
  WALK_EDGE_FAIL: "WALK_EDGE_FAIL",

  IO_NO_INVENTORIES: "IO_NO_INVENTORIES",
  IO_DEST_FULL: "IO_DEST_FULL",
  IO_PRECHECK_FAILED: "IO_PRECHECK_FAILED",
  IO_EXTRACT_FAILED: "IO_EXTRACT_FAILED",
});

export const ReasonLabels = Object.freeze({
  [ReasonCodes.NO_EDGE_GRAPH]: "no_edge_graph",
  [ReasonCodes.NO_ADJACENT_INV]: "no_adjacent_inv",
  [ReasonCodes.INV_EMPTY]: "inv_empty",
  [ReasonCodes.RESOLVE_NONE]: "resolve_none",
  [ReasonCodes.THROTTLED]: "throttled",
  [ReasonCodes.MUTATION_FAIL]: "mutation_fail",
  [ReasonCodes.EXPORT_THROTTLED]: "export_throttled",
  [ReasonCodes.EXPORT_NO_INVENTORIES]: "export_no_inventory",
  [ReasonCodes.EXPORT_NO_ITEMS]: "export_no_items",

  [ReasonCodes.RESOLVE_NO_ATTUNED]: "resolve_no_attuned",
  [ReasonCodes.RESOLVE_ATTUNED_FULL]: "resolve_attuned_full",
  [ReasonCodes.RESOLVE_ATTUNED_NO_PATH]: "resolve_attuned_no_path",
  [ReasonCodes.RESOLVE_DRIFT_ALL_FILTERED]: "resolve_drift_filtered",
  [ReasonCodes.RESOLVE_DRIFT_NO_INVENTORIES]: "resolve_drift_no_inventory",
  [ReasonCodes.RESOLVE_DRIFT_ALL_FULL]: "resolve_drift_full",
  [ReasonCodes.RESOLVE_DRIFT_NO_PATH]: "resolve_drift_no_path",
  [ReasonCodes.RESOLVE_CRUCIBLE_NO_PATH]: "resolve_crucible_no_path",
  [ReasonCodes.RESOLVE_FOUNDRY_NO_PATH]: "resolve_foundry_no_path",
  [ReasonCodes.RESOLVE_SAME_CONTAINER]: "resolve_same_container",
  [ReasonCodes.ILLEGAL_MUTATION_DETECTED]: "illegal_mutation_detected",
  [ReasonCodes.ILLEGAL_MUTATION_BLOCKED]: "illegal_mutation_blocked",
  [ReasonCodes.TRANSFER_WITHOUT_INFLIGHT]: "transfer_without_inflight",
  [ReasonCodes.SPAWN_EXTRACT]: "spawn_extract",
  [ReasonCodes.SETTLEMENT_INSERT]: "settlement_insert",
  [ReasonCodes.EXTRACT_WITHOUT_RESOLVE]: "extract_without_resolve",
  [ReasonCodes.SPAWN_WITHOUT_PATH]: "spawn_without_path",
  [ReasonCodes.SETTLE_WITHOUT_INFLIGHT]: "settle_without_inflight",
  [ReasonCodes.SETTLE_SAME_TICK_AS_SPAWN]: "settle_same_tick_as_spawn",
  [ReasonCodes.SETTLE_TOO_FAST]: "settle_too_fast",

  [ReasonCodes.EDGE_MISSING_PRECHECK]: "edge_missing",
  [ReasonCodes.EDGE_BROKEN_DROP]: "edge_drop",

  [ReasonCodes.WALK_NO_ATTUNED]: "walk_no_attuned",
  [ReasonCodes.WALK_DRIFT_LOST]: "walk_drift_lost",
  [ReasonCodes.WALK_DRIFT_ROUTE]: "walk_drift_route",
  [ReasonCodes.WALK_EDGE_FAIL]: "walk_edge_fail",

  [ReasonCodes.IO_NO_INVENTORIES]: "io_no_inventory",
  [ReasonCodes.IO_DEST_FULL]: "io_dest_full",
  [ReasonCodes.IO_PRECHECK_FAILED]: "io_precheck_failed",
  [ReasonCodes.IO_EXTRACT_FAILED]: "io_extract_failed",
});
